// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/core/domain/explorer/explorer.go
//
// Generated by this command:
//
//	mockgen -source=./internal/core/domain/explorer/explorer.go -package mocks -destination=./internal/core/domain/explorer/mocks/explorer.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	explorer "github.com/rm-ryou/gotor/internal/core/domain/explorer"
	gomock "go.uber.org/mock/gomock"
)

// MockFSReader is a mock of FSReader interface.
type MockFSReader struct {
	ctrl     *gomock.Controller
	recorder *MockFSReaderMockRecorder
	isgomock struct{}
}

// MockFSReaderMockRecorder is the mock recorder for MockFSReader.
type MockFSReaderMockRecorder struct {
	mock *MockFSReader
}

// NewMockFSReader creates a new mock instance.
func NewMockFSReader(ctrl *gomock.Controller) *MockFSReader {
	mock := &MockFSReader{ctrl: ctrl}
	mock.recorder = &MockFSReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFSReader) EXPECT() *MockFSReaderMockRecorder {
	return m.recorder
}

// ReadDir mocks base method.
func (m *MockFSReader) ReadDir(path string, depth int) ([]*explorer.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", path, depth)
	ret0, _ := ret[0].([]*explorer.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockFSReaderMockRecorder) ReadDir(path, depth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockFSReader)(nil).ReadDir), path, depth)
}
